version: "3.7"

volumes:
  data-graphite:

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    hostname: graphite
    volumes:
      - data-graphite:/opt/graphite/storage
    ports:
      - "9097:8888"
      - "9098:80"
      - "12003-12004:2003-2004"
      - "12023-12024:2023-2024"
      - "18125:8125/udp"
      - "18126:8126"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.100

  spark-master:
    image: frkhit/docker-spark-cluster-master:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.2
    volumes:
       - ./data/spark-apps:/opt/spark-apps
       - ./data/spark-data:/opt/spark-data
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "PYSPARK_PYTHON=python3"
    depends_on:
      - graphite

  spark-worker-1:
    image: frkhit/docker-spark-cluster-worker:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
      - graphite
    ports:
      - "8081:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-1"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.3
    volumes:
       - ./data/spark-apps:/opt/spark-apps
       - ./data/spark-data:/opt/spark-data

  spark-worker-2:
    image: frkhit/docker-spark-cluster-worker:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
      - graphite
    ports:
      - "8082:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-2"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.4
    volumes:
       - ./data/spark-apps:/opt/spark-apps
       - ./data/spark-data:/opt/spark-data
       
  spark-worker-3:
    image: frkhit/docker-spark-cluster-worker:latest
    container_name: spark-worker-3
    hostname: spark-worker-3
    depends_on:
      - spark-master
      - graphite
    ports:
      - "8083:8081"
    env_file: ./env/spark-worker.sh
    environment:
      - "SPARK_LOCAL_IP=spark-worker-3"
    networks: 
      spark-network:
        ipv4_address: 10.5.0.5
    volumes:
       - ./data/spark-apps:/opt/spark-apps
       - ./data/spark-data:/opt/spark-data

networks:
  spark-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16